config/routes.rb
Wishlist::Application.routes.draw do
  
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    resources :lists do
      resources :items do
        post :claim
        post :unclaim
      end
    end
  end
  
  resources :lists do
    resources :items do
      post :claim
      post :unclaim
    end
  end
  
  
  get "wishlist" => "users#wishlist", :as => "wishlist"

  root :to => "welcome#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :user_id, :comment
  
  has_many :items, dependent: :destroy
  belongs_to :user
  
  def images
    if items
      images = []
      items.each do |item|
        if item.product_image.url == "/product_images/original/missing.png"
          images << item.img_url
        else
          images << item.product_image.url(:medium)
        end
      end
      return images
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
    @list = List.find(params[:id])
    @items = @list.items.available.order("created_at DESC")
    @claimed_items = @list.items.claimed.order("created_at DESC")
  end
  respond_to do |format|
    format.html { redirect_to user_list_url(@list.user, @list)}
    format.js
  end
  
  def new
    @list = List.new
  end
  
  def edit
    @list - List.find(params[:id])
  end
  
  def create
    @user = User.find(params[:user_id])
    @list = @user.lists.create!(params[:list])
    respond_to do |format|
      # format.html { redirect_to user_list_url(@list.user, @list)}
      format.js
    end
    
    
  end
  
  def update
    @list = current_user.lists.find(params[:id])
    @list.update_attributes(params[:list])
    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end
  
  def destroy
    @list = current_user.lists.find(params[:id])
    @list.destroy
    respond_to do |format|
      format.html{ redirect_to root_url }
      format.js
    end
  end
end

app/views/lists/_ajax_new_form.html.haml
=form_for [current_user, @list], remote: :true do |f|
  =f.text_field :name, placeholder: "name", id: "new-list-field"
  =f.submit "create", id: "create-new-list", class: "button small"

app/views/lists/_index_list.html.haml
%a.index_list{ href: user_list_path(list.user, list)}
  .title_column
    .title=list.name
    .created-at
      =list.created_at.strftime("%b. %e, %Y")
  -if list.items.any?
    .count_column
      .item-count
        =pluralize(list.items.count, "item")
      .images
        -for image in list.images
          =image_tag image

app/views/lists/_list.html.haml
=link_to_unless_current("<div class='list-name'>#{list.name}</div><div class='count'>#{list.items.count}</div>".html_safe, user_list_path(list.user, list), class: "list-link") do
  .list{ id: "list_#{list.id}" }
    .list-name=list.name
    / .delete=link_to "X", list, method: :delete, data: {confirm: "Are you sure?"}
    
    .count=list.items.count
    

/ <div class= 'delete'>#{link_to "X", list, method: :delete, data: {confirm: "Are you sure?"}}</div>

app/views/lists/create.js.erb
if( $(".no_list").length > 0 ) {
  // on the index page
  $("#new_list").remove();
  $(".lists").prepend('<%= j render(@list) %>');
  $("#new_list_link").show();
  $("p.instructions").remove();
  $(".header-text").text("Your Wishlists:");
  $("img.no-list").remove();
  $(".index_lists").show();
  $(".index_lists").prepend('<%= j render(:partial => 'lists/index_list', :locals => {:list => @list}) %>');
} else{
  // on the sidebar
  $("#new_list").remove();
  $(".lists").prepend('<%= j render(@list) %>');
  $("p.instructions").remove();
  $(".header-text").text("Your Wishlists:");
  $("img.no-list").remove();
  $(".index_lists").show();
  $(".index_lists").prepend('<%= j render(:partial => 'lists/index_list', :locals => {:list => @list}) %>');
  $("#new_list_link").show();
}

app/views/lists/new.js.erb
if( $("#new-list-index").length > 0 && ($(".mask").attr("style") === "display: none;") || $(".mask").attr("style") === undefined ){
  // one the index page
  $("p.instructions").hide().after('<%= j render("lists/ajax_new_form") %>');
  
} else if($("#new-list-index").length > 0 && $(".mask").attr("style") === "display: block;"){
  // on the sidebar
  
  $("#new_list_link").hide().after('<%= j render("lists/ajax_new_form") %>');
    
} else{
  $("#new_list_link").hide().after('<%= j render("lists/ajax_new_form") %>');
}
$("#new-list-field").focus();

app/views/lists/show.html.haml
-session[:return_to] = request.fullpath
.inner_wrapper

  .list_container
    %h1.list-header=@list.name

    -if @list.user == current_user
      .owner This is your wishlist
  
    -else
      .owner
        =image_tag @list.user.image_url
        .name="#{@list.user.username}'s wishlist".html_safe

    .close
      =link_to "X", root_path
    -if @list.user == current_user
      .delete_list
        =link_to "Delete List", @list, method: :delete, data: {confirm: "Are you sure you would like to permanently delete this list?"}, class: "remove-list"
      .add_item
        =link_to "+ Add an Item", new_user_list_item_path(current_user, @list), id: "new_item_link", class: "button", remote: true
    
    .items
      -if @list.items.any?
        =render @items
    %h2.unavail{style: "display:none;"} Fulfilled  
    .unavailable_items{style: "display:none;"}
    -if @claimed_items.any?
      %h2.unavail Fulfilled  
      .unavailable_items
        =render @claimed_items