config/routes.rb
Wishlist::Application.routes.draw do
  
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do
    resources :lists do
      resources :items do
        post :claim
        post :unclaim
      end
    end
  end
  
  resources :lists do
    resources :items do
      post :claim
      post :unclaim
    end
  end
  
  
  get "wishlist" => "users#wishlist", :as => "wishlist"

  root :to => "welcome#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price, :store, :url, :user_id, :img_url, :claimed, :claimed_by, :list_id, :comment, :product_image
  
  has_attached_file :product_image, :styles => { 
    :medium => ["150x150>", :jpg]
    },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :bucket => "wishlist_#{Rails.env}",
    :url => "/items/:id/:style/:basename.:extension",
    :path => "/items/:id/:style/:filename"
    
  validates_attachment_content_type :product_image, :content_type => [ 'image/gif', 'image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :product_image, :less_than => 5.megabytes
  
  belongs_to :list
  
  scope :available, where("claimed is not true")
  scope :claimed, where("claimed is true")
  
  after_update :check_info
  
  def fetch_info(url)
    require 'open-uri'
    doc = Nokogiri::HTML(open(url))
    store = parse_url(url)
    
    # name = check_meta_name(doc)
    # image = check_meta_image(doc)
    
    # Amazon Specific info
    if store == "Amazon"
      if doc.at_css("#btAsinTitle")
        name = doc.at_css("#btAsinTitle").text
      elsif doc.at_css("h1#title")
        name = doc.at_css("h1#title").text
      else
        name = "unknown"
      end
      
      if doc.at_css(".priceLarge")
        price = doc.at_css(".priceLarge").text[/\d+(\.\d{1,2})?/]
      elsif doc.at_css(".a-color-price")
        price = doc.at_css(".a-color-price").text[/\d+(\.\d{1,2})?/]
      else
        price = "unknown"
      end
      
      if doc.at_css("#prodImageCell img")
        image = doc.at_css("#prodImageCell img")[:src]
      elsif doc.at_css("#main-image")
        image = doc.at_css("#main-image")[:src]
      elsif doc.at_css(".kib-image-ma")
        image = doc.at_css(".kib-image-ma")[:src]
      else
        image = nil
      end
    
    # Walmart Specific info
    elsif store == "Walmart"
      name = doc.at_css(".productTitle").text
      price = doc.at_css(".camelPrice").text
      imgage = doc.at_css(".LargeItemPhoto215 a")[:href]
    
    # Bestbuy Specific info
    elsif store == "Bestbuy"
      name = doc.at_css("#sku-title").text
      price = doc.at_css(".item-price").text
      image = doc.at_css(".image-gallery-main-slide a img")[:src]
    
    # Apple Specific info
    elsif store == "Apple"
      
      if doc.at_css(".heading.heading-hero h1.title")
        name = doc.at_css(".heading.heading-hero h1.title").text.strip
        name = name.gsub("Configure your ", '')
      elsif doc.at_css(".header h1")
        name = doc.at_css(".header h1").text.strip
        name = name.gsub("Select an ", '')
      elsif doc.at_css(".header h2")
        name = doc.at_css(".header h2").text.strip
        name = name.gsub("Select an ", '')
      end
      
      if doc.at_css("#purchase-info-primary .value")
        price = doc.at_css("#purchase-info-primary .value").text
      elsif doc.at_css(".option-1")
        price = doc.at_css(".option-1 .price nobr").text
      end
      
      if doc.at_css(".hero-img")
        image = doc.at_css(".hero-img")[:src]
      elsif doc.at_css("img.hero")
        image = doc.at_css("img.hero")[:src]
      end
      
    # Sears Specific info
    elsif store == "Sears"
      name = doc.at_css(".productName h1").text
      price = doc.at_css(".youPay .pricing").text
      image = doc.at_css("#productMainImage img")[:src]
    
    # Nordstrom Specific info
    elsif store == "Nordstrom"
      name = doc.at_css(".rightcol h1").text
      price = doc.at_css("span.price").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css(".fashion-photo-wrapper img")[:src]
    
    # Macys Specific info
    elsif store == "Macys"
      name = doc.at_css("#productTitle").text
      price = doc.at_css(".standardProdPricingGroup span:last").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#mainImage")[:src]
    
    # Etsy Specific info
    elsif store == "Etsy"
      name = doc.at_css("#item-title h1").text
      price = doc.at_css(".secondary .item-amount .currency-value").text[/^[\d]+\.[\d]{0,2}/]
      image = doc.at_css("#fullimage_link1 img")[:src]
    
    # REI Specific info
    elsif store == "REI"
      name = doc.at_css("#product h1").text
      price = doc.at_css(".price").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#featuredImg")[:src]
      image = "http://www.rei.com" + image
    
    # The Gap Specific info, returns mostly unknown because of site's construction
    elsif store == "Gap"
      if doc.at_css("#productNameText")
        name = doc.at_css("#productNameText h1").text.strip
      else
        name = doc.at_css("title").text
      end
      if doc.at_css("#priceText")
        price = doc.at_css("#priceText").text
      else
        price = "unknown"
      end
      image = nil
    
    # J. Crew Specific info
    elsif store == "J. Crew"
      name = doc.at_css("h1").text
      price = doc.at_css(".price-single").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#mainImg")[:src]
    
    # Banana Republic Specific info
    elsif store == "Banana Republic"
      if doc.at_css("#productNameText")
        name = doc.at_css("#productNameText h1").text.strip
      else
        name = doc.at_css("title").text
      end
      if doc.at_css("#priceText")
        price = doc.at_css("#priceText").text
      else
        price = "unknown"
      end
      image = nil
    
    # Bed Bath and Beyond Specific info
    elsif store == "Bed Bath and Beyond"
      name = doc.at_css(".producttitle").text
      price = doc.at_css("tr:nth-child(4) td:nth-child(6)").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css(".ppprodimageline:nth-child(2) img")[:src]
      image = "http://www.bedbathandbeyond.com" + image
    
    # Everlane Specific info
    elsif store == "Everlane"
      name = String.new(doc.at_css("title").text.strip)
      name = name.gsub(" - Everlane", "")
      name = name.parameterize
      name = name.gsub(/na-s/, "n's")
      name = name.gsub("-", " ")
      name = name.titleize
      price = doc.at_css("#prices-container").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#primary-image")[:src]
    
    # Warby Parker Specific info
    elsif store == "Warby Parker"
      if doc.at_css(".productName")
        name = doc.at_css(".productName h1").text
      else
        name = doc.at_css(".product-name h1").text
      end
      price = doc.at_css(".price").text[/\d+(\.\d{1,2})?/]
      if doc.at_css(".framePic")
        image = doc.at_css(".framePic img")[:src]
      else
        image = doc.at_css(".toggle img")[:src]
      end
    
    # Target Specific info
    elsif store == "Target"
      name = doc.at_css(".product-name").text.strip
      price = doc.at_css(".offerPrice").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#heroImage")[:src]
    
    # Williams and Sonoma Specific info
    elsif store == "Williams and Sonoma"
      name = doc.at_css("h1").text
      price = doc.at_css(".price-amount").text
      image = doc.at_css("#hero")[:src]
      
    # Uncrate Specific info
    elsif store == "Uncrate"
      name = doc.at_css("h1 a").text
      price = doc.at_css(".abide").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("img.xl")[:src]
    
    elsif store == "Kickstarter"
      name = doc.at_css("#title").text
      price = "various"
      image = doc.at_css("img")[:src]
    
    elsif store == "Newegg"
      name = doc.at_css("h1 span").text.strip
      price = "unknown"
      image = doc.at_css(".mainSlide img")[:src]
    
    elsif store == "Pier 1"
      name = doc.at_css(".product-name").text.strip
      price = doc.at_css(".price-standard").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css(".primary-image")[:src]
      
    elsif store == "Pottery Barn"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".price-amount").text
      image = doc.at_css("#hero")[:src]
      
    elsif store == "Crate & Barrel"
      name = doc.at_css("#_productTitle").text.strip
      price = doc.at_css(".regPrice").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#_imgLarge")[:src]
    
    elsif store == "kmart"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".pricing").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#productMainImage img")[:src]
    
    elsif store == "jcp"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".gallery_page_price").text[/\d+(\.\d{1,2})?/]
      image = doc.at_xpath("//meta[@property='og:image']/@content").value
      image = "http:" + image
    
    elsif store == "Costco"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".product-price").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#large_images img")[:src]
    
    elsif store == "World Market"
      name = doc.at_css(".detailheader").text.strip
      price = doc.at_css(".singlePrice").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#mainimage")[:src]
    
    elsif store == "Sierra Trading Post"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".salePrice").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#largeImage")[:src]
      
    elsif store == "Eddie Bauer"
      name = doc.at_css("h1.title").text.strip
      price = doc.at_css(".priceWrap").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css(".mainImage img")[:src]
    
    elsif store == "L.L. Bean"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".toOrderItemPrice").text[/\d+(\.\d{1,2})?/]
      image = doc.at_xpath("//meta[@property='og:image']/@content").value
    
    elsif store == "Powell's"
      name = doc.at_css(".book-title").text.strip
      price = doc.at_css(".price").text[/\d+(\.\d{1,2})?/]
      image = doc.at_css("#cover")[:src]
    
    elsif store == "Barnes and Noble"
      name = doc.at_css("h1").text.strip
      price = doc.at_css(".price").text[/\d+(\.\d{1,2})?/]
      image = doc.at_xpath("//meta[@property='og:image']/@content").value
    
    elsif store == "Steam"
      name = doc.at_css(".apphub_AppName").text.strip

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # respond_to :html, :json, :js
  load_and_authorize_resource
  def show
    @item = Item.find(params[:id])
    respond_to do |format|
      format.html { redirect_to user_item_url(@item.user, @item)}
      format.js
    end
  end
  
  def new
    @item = Item.new
    
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.create!(params[:item])
    respond_to do |format|
      format.html { redirect_to user_list_item_url(current_user, @list, @item)}
      format.js
    end
  end
  
  def update
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])
    @item.update_attributes(params[:item])
    respond_to do |format|
      format.html { redirect_to @list }
      format.js
    end
  end
  
  def destroy
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end
  
  def claim
    @item = Item.find(params[:item_id])
    @item.update_attributes(claimed: true, claimed_by: current_user.id)
    respond_to do |format|
      format.html { redirect_to user_item_url(@item.user, @item) }
      format.js
    end
  end
  
  def unclaim
    @item = Item.find(params[:item_id])
    @item.update_attributes(claimed: false, claimed_by: nil)
    respond_to do |format|
      format.html { redirect_to user_item_url(@item.user, @item) }
      format.js
    end
  end
  
  def update_with_info
    @list = List.find(params[:id])
    @item = @list.items.find(params[:item_id])
  end
end

app/views/items/_ajax_new_form.html.haml
=form_for [List.find(params[:list_id]), @item], remote: :true do |f|
  .form_instructions
    %strong
      Step 1: 
    copy/paste the url for the item that you would like to add
  .url_bar
    =f.text_field :url, class: "new_url"
  .actions
    =link_to "cancel", "#", class: "dismiss-url button cancel small"
    =f.submit "Go!", id: "find-new-item-submit", class: "button small"

app/views/items/_ajax_update_form.html.haml
=form_for [@list, @item], remote: :true do |f|
  .form_instructions
    %strong
      Step 2: 
    Make sure the details are correct
  -array = @item.fetch_info(@item.url)
  -image = array[4]
  .image_column
    -if image.nil?
      =image_tag "default_image.png", class: "product_image_option", id: "upload"
      =f.hidden_field :img_url, value: "default_image.png", class: "final_product_image"
      couldn't find an image, would you like to
      =link_to "upload your own?", "#", id: "replace-image"
    -else
      =image_tag image, class: "product_image_option", id: "upload"
      =f.hidden_field :img_url, value: image, class: "final_product_image"
      will this image work, or would you like to
      =link_to "upload your own?", "#", id: "replace-image"
    .file_field_wrapper
      =f.file_field :product_image, onchange: "readURL(this);"
  .info_column
    =f.hidden_field :store, value: array[3]
    %p
      =f.label :name, "Item:"
      =f.text_field :name, value: array[0]
    %p.price
      =f.label :price, "Price: $"
      =f.text_field :price, value: array[1]
    %p.comment
      =f.text_area :comment, placeholder: "Additional Information (optional)"
    %p.submit
      =link_to "Cancel", [@item.list, @item], method: :delete, remote: true, class: "cancel-item button cancel small"
      =f.submit "Looks Good!", id: "add-to-wishlit-submit", class: "button small"
:javascript
  function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#upload').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
      }
  }

app/views/items/_item.html.haml
.item{ id: "item_#{item.id}", class: item.claimed ? "claimed" : "" }
  .actions
    -if current_user
      -if item.claimed?
        -if item.claimed_by == current_user.id
          .claim.unclaim_button
            .check-mark
            =button_to "", user_list_item_unclaim_path(item.list, current_user, item), remote: true
            .message
              undo
        -claimer =item.claimed_by_user.username
        -if claimer == current_user.username
          %span.claimed-by
            you claimed this
        -else
          -if item.list.user == current_user
            %span.claimed-by
              item has been claimed
          -else
            %span.claimed-by
              =claimer
              claimed this
      -unless item.claimed?
        .claim.claim_button
          .check-mark
          =button_to "", user_list_item_claim_path(item.list, current_user, item), remote: true
          .message
            fulfill item
    -else
      .claim.sign_up
        .check-mark
        =link_to "sign in to fulfill this item", user_omniauth_authorize_path(:facebook), class: "fb-sign-in"
        .message
          click to login
  .image
    -if item.product_image.url != "/product_images/original/missing.png"
      =image_tag item.product_image.url(:medium)
    -else
      =image_tag item.img_url
  .info
    -if can? :destroy, item
      =link_to "X remove", [item.list, item], method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: "remove-item"
    .title
      =link_to item.name, item.url, target: "blank"
    .price
      =number_to_currency item.price
      

app/views/items/claim.js.erb
var item = $("#item_<%= @item.id %>.item");
item.addClass("claimed");
$("#item_<%= @item.id %>.item form").after("<span class='claimed-by'>you claimed this</span>");
$("#item_<%= @item.id %>.item .message").hide();
$("#item_<%= @item.id %>.item form").remove();
item.remove();
$("h2.unavail").show();
$(".unavailable_items").show();

$(".unavailable_items").prepend("<%= j render(@item) %>");

app/views/items/create.js.erb
$("#new_item").remove();
$(".show-hide").hide().after('<%= j render("items/ajax_update_form") %>');

app/views/items/destroy.js.erb
$("#item_<%= @item.id %>.item").remove();
$(".edit_item").remove();
$("#new_item_link").show();
$(".items").css("margin-top", "0px");
$(".new_item_container").removeClass("pop_out");
$(".mask").fadeOut();

var id = <%= @item.list.id %>;
var num = parseInt($("#list_" + id + ".list").find(".count").text());
$("#list_" + id + ".list").find(".count").text( num - 1);

app/views/items/get_info.html.haml
=@item.url

app/views/items/new.html.haml
=form_for [current_user, @item], remote: :true do |f|
  =f.label "copy/paste url:"
  .url_bar
    =f.text_field :url, class: "new_url"
    =f.submit "Find", class "button"

app/views/items/new.js.erb
$(".new_item_container").addClass("pop_out");
// $(".new_item_container").html("");
$(".new_item_container").prepend('<%= j render("items/ajax_new_form") %>');

$(".mask").fadeIn();

app/views/items/show.html.haml
=@item.url


=link_to "get info", user_item_update_with_info_path(current_user, @item)

app/views/items/unclaim.js.erb
var item = $("#item_<%= @item.id %>.item");
item.removeClass("claimed");
$("#item_<%= @item.id %>.item form").after("<span class='claimed-by'></span>");
$("#item_<%= @item.id %>.item .message").hide();
$("#item_<%= @item.id %>.item form").remove();
item.remove();
$(".items").prepend("<%= j render(@item) %>");

app/views/items/update.js.erb
<% if @item.name.blank? %>
  $(".edit_item").remove();
  $("#new_item_link").show();
  var id = <%= @item.list.id %>;
  var num = parseInt($("#list_" + id + ".list").find(".count").text());
  $("#list_" + id + ".list").find(".count").text( num + 1);
<% else %>
  $(".edit_item").remove();
  $("#new_item_link").show();
  $(".items").prepend('<%= j render(@item) %>');
  var id = <%= @item.list.id %>;
  var num = parseInt($("#list_" + id + ".list").find(".count").text());
  $("#list_" + id + ".list").find(".count").text( num + 1);
<% end %>

$(".new_item_container").removeClass("pop_out");
$(".mask").fadeOut();

app/views/items/update_with_info.html.haml
=form_for [current_user, @item] do |f|

  -array = @item.fetch_info(@item.url)
  -if array[2] == nil
    Sorry, could not find an image
  -else 
    =image_tag array[2]
    =f.hidden_field :img_url, value: array[2]
  %p
    =f.label :url
    =f.text_field :url, value: @item.url
  %p
    =f.label :store
    =f.text_field :store, value: array[4]
  %p
    =f.label :name
    =f.text_field :name, value: array[0]
  %p
    =f.label :price
    =f.text_field :price, value: array[1]
  
  %p
    =f.submit "Add to Wishlist"